project:
  type: website

website:
  title: "CentralStatz Statistical & Data Sciences LLC"
  favicon: "logo_background.png"
  google-analytics: "G-GQTNSLKV9S"
  site-url: https://www.centralstatz.com/
  repo-url: https://github.com/centralstatz/centralstatz
  description: "Data science, statistics, and analytics advising located in Central Wisconsin."
  page-footer: 
    center: |
        © 2026 CentralStatz Statistical & Data Sciences LLC
        <div class="footer-icons">
          <a href="mailto:alex@centralstatz.com" target="_blank"><i class="bi bi-envelope"></i></a>
          <a href="https://www.linkedin.com/company/centralstatz" target="_blank"><i class="bi bi-linkedin"></i></a>
          <a href="https://github.com/centralstatz" target="_blank"><i class="bi bi-github"></i></a>
          <a href="https://www.youtube.com/@centralstatz" target="_blank"><i class="bi bi-youtube"></i></a>
        </div>
  open-graph: true
  navbar:
    logo: "logo.png"
    title: false
    left:
          - text: What We Do
            href: "/#what-we-do"
          - text: Our Philosophy
            href: "/#our-philosophy"
          - text: About
            href: "/#about"
          - text: Contact
            href: "/#contact"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/centralstatz
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:alex@centralstatz.com
        aria-label: Email
format:
  html:
    theme: [styles.scss, lux]

editor: source

